data:
      raw_data_dir: "./data/raw/"
      processed_input_data_dir: "./data/processed/"
model:
      dim_ext_force: 0
      hidden_dim: 8
      num_MP_layers: 5
      seed: 8756
train:
      num_workers: 1
      train_data_size_to_use: 128
      batch_size: 16
      num_epochs: 100
      lr: 0.001
      weight_decay: 1e-4
      scheduler_step: 10
      scheduler_gamma: 0.98
